# Generated by Django 4.1.7 on 2023-06-14 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Gesco.customuser')),
                ('administration_status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Gesco.customuser',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Gesco.customuser')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('is_etudiant', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Gesco.customuser',),
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('auteur', models.CharField(max_length=30, null=True)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='media/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gesco.categorie')),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
    ]
