# Generated by Django 4.1.7 on 2023-06-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_Client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_Restaurateur',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='is_Restaurateur',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='username',
        ),
    ]
